tam:
- [ 0.7351,  0.7071,  0.7071,  0.7053, -0.0,   -0.0,   -0.0,   -0.0  ]   # Fx
- [-0.6779,  0.7071,  0.7071, -0.7089,  0.0,    0.0,    0.0,    0.0  ]   # Fy
- [ 0.0,     0.0,     0.0,     0.0,     1.0,    1.0,    1.0,    1.0  ]   # Fz
- [ 0.0136, -0.0141, -0.0141,  0.0142,  0.2346, -0.2344,  0.2346, -0.2344 ] # Mx
- [ 0.0147,  0.0141,  0.0141,  0.0141, -0.1562, -0.1562,  0.1638,  0.1637 ] # My
- [-0.1955,  0.1936, -0.1935,  0.1927,  0.0,   -0.0,    0.0,   -0.0  ]   # Mz

